/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.HoaDonChiTietDAO;
import dao.HoaDonDAO;
import dao.LoaiMonDAO;
import dao.ThongKeDAO;
import entity.HoaDon;
import entity.LoaiMon;
import entity.ThongKe;
import entity.ThongKe.DoanhThu;
import entity.ThongKe.DoanhThuCT;
import entity.ThongKe.DoanhThuMonAn;
import entity.ThongKe.NgayLap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLayeredPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.AreaRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import utils.MsgBox;

/**
 *
 * @author ADMIN
 */
public class ThongKeJFrame extends javax.swing.JFrame {

    LoaiMonDAO LMdao = new LoaiMonDAO();
    ThongKeDAO TKdao = new ThongKeDAO();
    HoaDonDAO dao = new HoaDonDAO();
    HoaDonChiTietDAO daoct = new HoaDonChiTietDAO();
    DecimalFormat fmTien = new DecimalFormat("#,#00");
    SimpleDateFormat fmThoiGian = new SimpleDateFormat("dd/MM");
    SimpleDateFormat fmThoiGianCT = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form ThongKeJFrame
     */
    public ThongKeJFrame() {
        setTitle("Hệ thống quản lý nhà hàng L'ESSALE - Thống Kê");
        initComponents();
        fillComboBoxLoaiMon();
        loadBieuDoMonAn();
        loadBieuDoDoanhThu();
        loadCboNgayLap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboLoaiMon = new javax.swing.JComboBox<>();
        pnlThongKe = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clrTuNgay = new com.toedter.calendar.JDateChooser();
        clrDenNgay = new com.toedter.calendar.JDateChooser();
        pnlDoanhThu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThuCT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        clrTuNgayCT = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        clrDenNgayCT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("LOẠI MÓN ĂN");

        cboLoaiMon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cboLoaiMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiMonActionPerformed(evt);
            }
        });

        pnlThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 873, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("DOANH SỐ MÓN ĂN", jPanel1);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("TỪ NGÀY");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("ĐẾN NGÀY");

        clrTuNgay.setDateFormatString("dd-MM-yyyy");
        clrTuNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                clrTuNgayPropertyChange(evt);
            }
        });

        clrDenNgay.setDateFormatString("dd-MM-yyyy");
        clrDenNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                clrDenNgayPropertyChange(evt);
            }
        });

        pnlDoanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout pnlDoanhThuLayout = new javax.swing.GroupLayout(pnlDoanhThu);
        pnlDoanhThu.setLayout(pnlDoanhThuLayout);
        pnlDoanhThuLayout.setHorizontalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDoanhThuLayout.setVerticalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 727, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clrTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clrDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("DOANH THU", jPanel2);

        tblDoanhThuCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hoá Đơn", "Ngày lập", "Mã Khách hàng", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblDoanhThuCT);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("TỪ NGÀY");

        clrTuNgayCT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                clrTuNgayCTPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("ĐẾN NGÀY");

        clrDenNgayCT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                clrDenNgayCTPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrTuNgayCT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrDenNgayCT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 668, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(clrTuNgayCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(clrDenNgayCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        tabs.addTab("DOANH THU CHI TIẾT", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiMonActionPerformed
        loadBieuDoMonAn();
    }//GEN-LAST:event_cboLoaiMonActionPerformed

    private void clrTuNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_clrTuNgayPropertyChange
        // TODO add your handling code here:
        loadCboNgayLap();
    }//GEN-LAST:event_clrTuNgayPropertyChange

    private void clrDenNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_clrDenNgayPropertyChange
        // TODO add your handling code here:
        loadCboNgayLap();
    }//GEN-LAST:event_clrDenNgayPropertyChange

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new TrangChuJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void clrTuNgayCTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_clrTuNgayCTPropertyChange
        loadCboNgayLapCT();
    }//GEN-LAST:event_clrTuNgayCTPropertyChange

    private void clrDenNgayCTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_clrDenNgayCTPropertyChange
        loadCboNgayLapCT();
    }//GEN-LAST:event_clrDenNgayCTPropertyChange

    /**
     * @param args the command line arguments
     */
    public void selectTab(int index){
        tabs.setSelectedIndex(index);
    }
    
    void fillComboBoxLoaiMon() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiMon.getModel();
        model.removeAllElements();
        model.addElement("All");
        List<LoaiMon> list = LMdao.selectAll();
        for (LoaiMon lm : list) {
            model.addElement(lm);
        }
    }

//    void fillTableMonAn() {
//        DefaultTableModel model = (DefaultTableModel) tblMonAn.getModel();
//        model.setRowCount(0);
//        tblMonAn.setModel(model);
//        LoaiMon lm = (LoaiMon) cboLoaiMon.getSelectedItem();
//        List<Object[]> list = TKdao.getSum(Integer.parseInt(lm.getMaLoai()));
//        for (Object[] row : list) {
//            double soluong = (double) row[2];
//            model.addRow(new Object[]{
//                row[0], row[1], soluong
//            });
//        }
//    }
    
    public void loadCboNgayLap(){
        NgayLap nl = TKdao.getNgayLap();
        
        if( clrDenNgay.getDate() == null || clrTuNgay.getDate() == null){
            clrTuNgay.setSelectableDateRange(nl.getMin(), nl.getMax());
            clrDenNgay.setSelectableDateRange(nl.getMin(), nl.getMax());
            clrTuNgay.setDate(nl.getMin());
            clrDenNgay.setDate(nl.getMax());
            return;
        }
        
        
        clrTuNgay.setMaxSelectableDate(clrDenNgay.getDate());
        clrDenNgay.setMinSelectableDate(clrTuNgay.getDate());
        
        clrTuNgay.repaint();
        clrDenNgay.repaint();
        
        System.out.println("ui.ThongKeJFrame.loadCboNgayLap()");
        
        loadBieuDoDoanhThu();
    }
    
    public void loadCboNgayLapCT(){
        NgayLap nl = TKdao.getNgayLap();
        
        if( clrDenNgayCT.getDate() == null || clrTuNgayCT.getDate() == null){
            clrTuNgayCT.setSelectableDateRange(nl.getMin(), nl.getMax());
            clrDenNgayCT.setSelectableDateRange(nl.getMin(), nl.getMax());
            clrTuNgayCT.setDate(nl.getMin());
            clrDenNgayCT.setDate(nl.getMax());
            return;
        }
        
        
        clrTuNgayCT.setMaxSelectableDate(clrDenNgayCT.getDate());
        clrDenNgayCT.setMinSelectableDate(clrTuNgayCT.getDate());
        
        clrTuNgayCT.repaint();
        clrDenNgayCT.repaint();
        
        System.out.println("ui.ThongKeJFrame.loadCboNgayLapCT()");
        
        fillTable();
    }
    
    public void loadBieuDoDoanhThu() {
        List<DoanhThu> list = TKdao.getDoanhThu(clrTuNgay.getDate(), clrDenNgay.getDate());

        double[] data = new double[]{};
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(DoanhThu dt : list){
            dataset.addValue(dt.getTongTien(), "Tổng Tiền", fmThoiGian.format(dt.getNgayLap()));
        }
        // 1. Tạo dữ liệu cho biểu đồ miền
        
        

        // 2. Tạo biểu đồ miền
        JFreeChart areaChart = ChartFactory.createAreaChart("Biểu đồ doanh thu", // Tiêu đề biểu đồ
                "Thời Gian",                        // Nhãn trục x
                "Tổng Tiền", 
                dataset,                        // Dữ liệu
                PlotOrientation.VERTICAL,       // Hướng của biểu đồ
                false,                           // Hiển thị chú thích
                true,                           // Hiển thị tooltip
                false                           // URL generation
        );

        CategoryPlot plot = (CategoryPlot) areaChart.getPlot();
        AreaRenderer renderer = new AreaRenderer();
        renderer.setBaseToolTipGenerator(new StandardCategoryToolTipGenerator(
                "{1} - {2}đ",
                NumberFormat.getInstance()
        ));
        plot.setRenderer(renderer);
        
        // 3. Tạo ChartPanel từ JFreeChart
        ChartPanel chartPanel = new ChartPanel(areaChart);
        
        pnlDoanhThu.removeAll();
        
        // Tạo ChartPanel từ biểu đồ và thiết lập kích thước
        chartPanel.setBounds(0, 0, pnlDoanhThu.getWidth(), pnlDoanhThu.getHeight());
        pnlDoanhThu.add(chartPanel, JLayeredPane.PALETTE_LAYER);

        // Cập nhật giao diện
        pnlDoanhThu.revalidate();
        pnlDoanhThu.repaint();

    }

    public void loadBieuDoMonAn() {
        LoaiMon lm = null;
        if (cboLoaiMon.getSelectedIndex() == 0) {
            lm = new LoaiMon("%", "%");
        } else {
            lm = (LoaiMon) cboLoaiMon.getSelectedItem();
        }

        if (lm == null) {
            return;
        }
        List<DoanhThuMonAn> list = TKdao.getSum(lm.getMaLoai());

        // Tạo dataset mới cho biểu đồ
        DefaultPieDataset dataset = new DefaultPieDataset();
        for (DoanhThuMonAn lm1 : list) {
            dataset.setValue(lm1.getTenMon(), lm1.getSoLuong());
        }

        // Tạo biểu đồ mới với dữ liệu
        JFreeChart chart = ChartFactory.createPieChart(
                "Món ăn", // Tiêu đề biểu đồ
                dataset, // Dữ liệu biểu đồ
                false,
                true,
                false

        );

        // Lấy đối tượng PiePlot từ biểu đồ
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0} - {2}"));
        // {0} Tên dữ liệu
        // {1} giá trị dữ liệu
        // {2} giá trị dữ liệu theo phần trăm
        // {3} tổng các giá trị

        // Xóa các thành phần cũ trong pnlThongKe
        pnlThongKe.removeAll();

        // Tạo ChartPanel từ biểu đồ và thiết lập kích thước
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBounds(0, 0, pnlThongKe.getWidth(), pnlThongKe.getHeight());
        pnlThongKe.add(chartPanel, JLayeredPane.PALETTE_LAYER);

        // Cập nhật giao diện
        pnlThongKe.revalidate();
        pnlThongKe.repaint();

    }
    
    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuCT.getModel();
        model.setRowCount(0);
        try {
        List<DoanhThuCT> list = TKdao.getDoanhThuCT(clrTuNgayCT.getDate(), clrDenNgayCT.getDate());
        for (DoanhThuCT dt : list) {
            try {
                double tongTien = daoct.selectSum(dt.getMaHD());
                Object[] row = {
                    dt.getMaHD(),
                    fmThoiGianCT.format(dt.getNgayLap()),
                    dt.getMaKH(),
                    fmTien.format(tongTien)
                };
                model.addRow(row);
            } //        } catch (Exception e) {
            //            MsgBox.alert(this, "Lỗi truy vần dữ liệu!");
            //        }
            catch (SQLException ex) {
                Logger.getLogger(QuanLyHoaDonJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
} catch (Exception e) {
        // Thông báo lỗi nếu có vấn đề với việc lấy danh sách
        MsgBox.alert(this, "Lỗi khi lấy danh sách doanh thu!");
    }
        }

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoaiMon;
    private com.toedter.calendar.JDateChooser clrDenNgay;
    private com.toedter.calendar.JDateChooser clrDenNgayCT;
    private com.toedter.calendar.JDateChooser clrTuNgay;
    private com.toedter.calendar.JDateChooser clrTuNgayCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDoanhThuCT;
    // End of variables declaration//GEN-END:variables
}
