/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import dao.ThongKeDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import utils.Auth;
import utils.MsgBox;

/**
 *
 * @author admin
 */
public class TrangChuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuJFrame1
     */
    ThongKeDAO tkDAO = new ThongKeDAO();
    DecimalFormat fmTien = new DecimalFormat("#,#00");

    public TrangChuJFrame() {
        initComponents();
        setChucVu();
        init();

        ImageIcon icon = new ImageIcon("./img/logo.jpg");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnMonAn = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDoanhThuQuanLy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniMonAn = new javax.swing.JMenuItem();
        mniHoaDon = new javax.swing.JMenuItem();
        mniBanHang = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniDoanhThuChiTiet = new javax.swing.JMenuItem();
        mniDoanhSo = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHDSD = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnuFill = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton7.setBackground(new java.awt.Color(255, 0, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Address book.png"))); // NOI18N
        jButton7.setText("GIỚI THIỆU");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(255, 0, 51));
        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Price list.png"))); // NOI18N
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnMonAn.setBackground(new java.awt.Color(255, 0, 51));
        btnMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMonAn.setForeground(new java.awt.Color(255, 255, 255));
        btnMonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dish (1).png"))); // NOI18N
        btnMonAn.setText("MÓN ĂN");
        btnMonAn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMonAn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMonAn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonAnActionPerformed(evt);
            }
        });

        btnBanHang.setBackground(new java.awt.Color(255, 0, 51));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Computer.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanHang.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(255, 0, 51));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnKetThuc.setBackground(new java.awt.Color(255, 0, 51));
        btnKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Unlock.png"))); // NOI18N
        btnKetThuc.setText("KẾT THÚC");
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 255, 255));
        lblDongHo.setText("00:23:00 SA");
        jPanel2.add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 110, -1));

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setText("Quản lý:");
        jPanel2.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 360, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CẦN THƠ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 180, -1));

        jLabel7.setFont(new java.awt.Font("STZhongsong", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NHÀ HÀNG");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Wide Latin", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("L'ESCALE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lblDoanhThuQuanLy.setBackground(new java.awt.Color(255, 255, 255));
        lblDoanhThuQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDoanhThuQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThuQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoanhThuQuanLy.setText("<html>\n<div style=\"background-color: rgba(0, 0, 0, 0.5); padding: 5px 10px;\" >\n\t<p>Doanh thu hôm nay:</p>\n\t<p style=\"margin-top:10px\">Doanh thu tháng này:</p>\n\t<p style=\"margin-top:10px\">Số lượng bán hôm nay:</p>\n</div>\n</html>");
        lblDoanhThuQuanLy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblDoanhThuQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/400360970_913848526916133_5979970040266248220_n.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 510));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mnuHeThong.setBackground(new java.awt.Color(102, 102, 102));
        mnuHeThong.setForeground(new java.awt.Color(255, 255, 255));
        mnuHeThong.setText("HỆ THỐNG");
        mnuHeThong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuHeThong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuHeThong.setOpaque(true);
        mnuHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuHeThongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuHeThongMouseExited(evt);
            }
        });

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        jMenuItem6.setText("ĐĂNG XUẤT");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuHeThong.add(jMenuItem6);
        mnuHeThong.add(jSeparator5);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        jMenuItem7.setText("ĐỔI MẬT KHẨU");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuHeThong.add(jMenuItem7);
        mnuHeThong.add(jSeparator4);

        mnuKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lock.png"))); // NOI18N
        mnuKetThuc.setText("KẾT THÚC");
        mnuKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuKetThuc);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setBackground(new java.awt.Color(102, 102, 102));
        mnuQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        mnuQuanLy.setText("QUẢN LÝ");
        mnuQuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuQuanLy.setOpaque(true);
        mnuQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuQuanLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuQuanLyMouseExited(evt);
            }
        });

        mniMonAn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniMonAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniMonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dish (1).png"))); // NOI18N
        mniMonAn.setText("MÓN ĂN");
        mniMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMonAnActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniMonAn);

        mniHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Price list.png"))); // NOI18N
        mniHoaDon.setText("HÓA ĐƠN");
        mniHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHoaDonActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHoaDon);

        mniBanHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniBanHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Computer.png"))); // NOI18N
        mniBanHang.setText("BÁN HÀNG");
        mniBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBanHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniBanHang);
        mnuQuanLy.add(jSeparator6);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        mniNhanVien.setText("NHÂN VIÊN");
        mniNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setBackground(new java.awt.Color(102, 102, 102));
        mnuThongKe.setForeground(new java.awt.Color(255, 255, 255));
        mnuThongKe.setText("THỐNG KÊ");
        mnuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuThongKe.setOpaque(true);
        mnuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuThongKeMouseExited(evt);
            }
        });

        mniDoanhThuChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniDoanhThuChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        mniDoanhThuChiTiet.setText("DOANH THU CHI TIẾT");
        mniDoanhThuChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuChiTietActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThuChiTiet);

        mniDoanhSo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniDoanhSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Best.png"))); // NOI18N
        mniDoanhSo.setText("DOANH SỐ MÓN ĂN");
        mniDoanhSo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniDoanhSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhSoActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhSo);

        mniDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Diagram.png"))); // NOI18N
        mniDoanhThu.setText("DOANH THU THEO NĂM");
        mniDoanhThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThu);

        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setBackground(new java.awt.Color(102, 102, 102));
        mnuTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        mnuTroGiup.setText("TRỢ GIÚP");
        mnuTroGiup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuTroGiup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuTroGiup.setOpaque(true);
        mnuTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuTroGiupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuTroGiupMouseExited(evt);
            }
        });

        mniHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Control panel.png"))); // NOI18N
        mniHDSD.setText("HƯỚNG DẪN SỬ DỤNG");
        mniHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHDSDActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHDSD);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Address book.png"))); // NOI18N
        jMenuItem15.setText("GIỚI THIỆU");
        jMenuItem15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mnuTroGiup.add(jMenuItem15);

        jMenuBar1.add(mnuTroGiup);

        mnuFill.setBackground(new java.awt.Color(102, 102, 102));
        mnuFill.setText("                                                                                                                                                               ");
        mnuFill.setMargin(new java.awt.Insets(3, 50, 3, 50));
        mnuFill.setOpaque(true);
        jMenuBar1.add(mnuFill);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new LoginJFrame().setVisible(true);
        Auth.user = null;
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mniHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHoaDonActionPerformed
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openQLHoaDon();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniHoaDonActionPerformed

    private void mniBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBanHangActionPerformed
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openBanHang();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniBanHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openQLHoaDon();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonAnActionPerformed
        // TODO add your handling code here:
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openMonAn();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_btnMonAnActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed

        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openBanHang();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        new LoginJFrame().setVisible(true);
        Auth.user = null;
        dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new GioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void mnuHeThongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuHeThongMouseEntered
        // TODO add your handling code here:
        mnuHeThong.setBackground(new Color(70, 70, 70));
    }//GEN-LAST:event_mnuHeThongMouseEntered

    private void mnuHeThongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuHeThongMouseExited
        // TODO add your handling code here:
        mnuHeThong.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_mnuHeThongMouseExited

    private void mnuQuanLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyMouseEntered
        // TODO add your handling code here:
        mnuQuanLy.setBackground(new Color(70, 70, 70));
    }//GEN-LAST:event_mnuQuanLyMouseEntered

    private void mnuQuanLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyMouseExited
        // TODO add your handling code here:
        mnuQuanLy.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_mnuQuanLyMouseExited

    private void mnuThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThongKeMouseEntered
        // TODO add your handling code here:
        mnuThongKe.setBackground(new Color(70, 70, 70));
    }//GEN-LAST:event_mnuThongKeMouseEntered

    private void mnuThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThongKeMouseExited
        // TODO add your handling code here:
        mnuThongKe.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_mnuThongKeMouseExited

    private void mnuTroGiupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTroGiupMouseEntered
        // TODO add your handling code here:
        mnuTroGiup.setBackground(new Color(70, 70, 70));
    }//GEN-LAST:event_mnuTroGiupMouseEntered

    private void mnuTroGiupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTroGiupMouseExited
        // TODO add your handling code here:
        mnuTroGiup.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_mnuTroGiupMouseExited

    private void mnuKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKetThucActionPerformed
        // TODO add your handling code here:
        ketThuc();
    }//GEN-LAST:event_mnuKetThucActionPerformed

    private void mniMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMonAnActionPerformed
        // TODO add your handling code here:
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openMonAn();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniMonAnActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
       JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openNhanVien();
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniDoanhSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhSoActionPerformed
        // TODO add your handling code here:
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openThongKe(2);
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniDoanhSoActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        // TODO add your handling code here:
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openThongKe(0);
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new GioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void mniHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHDSDActionPerformed
        // TODO add your handling code here:
        openHDSD();
    }//GEN-LAST:event_mniHDSDActionPerformed

    private void mniDoanhThuChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuChiTietActionPerformed
        // TODO add your handling code here:
        JDialog JDWait = new WaitDialog(this, false);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                openThongKe(1);
                return null;
            }

            @Override
            protected void done() {
                JDWait.setVisible(false);
                JDWait.dispose();
            }
        };

        JDWait.setVisible(true);
        worker.execute();
    }//GEN-LAST:event_mniDoanhThuChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnMonAn;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDoanhThuQuanLy;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniBanHang;
    private javax.swing.JMenuItem mniDoanhSo;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoanhThuChiTiet;
    private javax.swing.JMenuItem mniHDSD;
    private javax.swing.JMenuItem mniHoaDon;
    private javax.swing.JMenuItem mniMonAn;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenu mnuFill;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuKetThuc;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    // End of variables declaration//GEN-END:variables

    void setChucVu() {
        if (!Auth.isManager()) {
            mnuThongKe.setVisible(false);
            mnuQuanLy.setVisible(false);

            btnHoaDon.setVisible(false);
            btnMonAn.setVisible(false);
            lblDoanhThuQuanLy.setVisible(false);

            mnuFill.setText(mnuFill.getText() + "                        ");
        } else {
            setDoanhThu();
            lblDoanhThuQuanLy.setVisible(true);
        }
        lblChucVu.setText((Auth.isManager() ? "Quản lý: " : "Nhân viên: ") + Auth.user.getTenNV());

    }

    void init() {
        setTitle("Hệ thống quản lý nhà hàng L'ESSALE");
        new Timer(1000, new ActionListener() {
            SimpleDateFormat fomat = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(fomat.format(new Date()));
            }
        }).start();

        setChucVu();
    }

    void setDoanhThu() {

        String doanhThuHomNay = fmTien.format(tkDAO.getDoanhThuHomNay()) + " VNĐ";
        String doanhThuThangNay = fmTien.format(tkDAO.getDoanhThuThang()) + " VNĐ";
        String soLuongBanHomNay = String.valueOf(tkDAO.getSoLuongBanHomNay());

        String textHTML = "<html><div style='background-color: rgba(0, 0, 0, 0.5); padding: 10px 30px 10px 10px;'>"
                + "<p>Doanh thu hôm nay: <span style='font-weight: bold;'>" + doanhThuHomNay + "</span></p>"
                + "<p style='margin-top:10px'>Doanh thu tháng này: <span style='font-weight: bold;'>" + doanhThuThangNay + "</span></p>"
                + "<p style='margin-top:10px'>Số lượng bán hôm nay: <span style='font-weight: bold;'>" + soLuongBanHomNay + "</span></p>"
                + "</div>"
                + "</html>";

        lblDoanhThuQuanLy.setText(textHTML);
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn có chắc muốn thoát không?")) {
            System.exit(0);
        }
    }

    void openMonAn() {
        new QuanLyMonAnJFrame().setVisible(true);
        dispose();
    }

    void openQLHoaDon() {
        new QuanLyHoaDonJFrame().setVisible(true);
        dispose();
    }

    void openBanHang() {
        new BanHangJFrame().setVisible(true);
        dispose();
    }
    
    void openNhanVien(){
        new NhanVienJFrame().setVisible(true);
        dispose();
    }
    
    void openThongKe(int tab){
        ThongKeJFrame TK = new ThongKeJFrame();
        TK.selectTab(tab);
        TK.setVisible(true);
        dispose();
    }
    public void openHDSD() {
        try {
            String projectDir = "./HDSD";

            // Tạo server tại địa chỉ 127.0.0.1 và cổng 5500
            HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 5500), 0);

            // Đăng ký handler cho mọi yêu cầu
            server.createContext("/", new HttpHandler() {
                @Override
                public void handle(HttpExchange exchange) throws IOException {
                    // Lấy đường dẫn của file được yêu cầu
                    String requestedFile = exchange.getRequestURI().getPath();

                    if (requestedFile.equals("/")) {
                        requestedFile = "/HDSD.html";
                    }

                    // Tạo đường dẫn đầy đủ tới file
                    Path filePath = Paths.get(projectDir, requestedFile);

                    // Kiểm tra xem file có tồn tại không
                    if (Files.exists(filePath) && !Files.isDirectory(filePath)) {
                        // Đoán loại nội dung và thiết lập header
                        String contentType = Files.probeContentType(filePath);
                        exchange.getResponseHeaders().set("Content-Type", contentType);

                        // Đọc nội dung file và gửi phản hồi
                        byte[] response = Files.readAllBytes(filePath);
                        exchange.sendResponseHeaders(200, response.length);
                        OutputStream output = exchange.getResponseBody();
                        output.write(response);
                        output.close();
                    } else {
                        // Nếu file không tồn tại, trả về lỗi 404
                        String errorMsg = "404 (Not Found)\n";
                        exchange.sendResponseHeaders(404, errorMsg.length());
                        OutputStream output = exchange.getResponseBody();
                        output.write(errorMsg.getBytes());
                        output.close();
                    }
                }
            });

            // Bắt đầu server
            server.setExecutor(null);
            server.start();
            System.out.println("Server đang chạy tại http://127.0.0.1:5500/");

            // Mở trình duyệt tự động
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().browse(new URI("http://127.0.0.1:5500/"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("Desktop không được hỗ trợ trên hệ thống này!");
            }
        } catch (IOException ex) {
            Logger.getLogger(TrangChuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
